import React, { useState } from 'react';
import { useApp } from '../context/AppContext';
import { Card } from './ui/Card';
import { Badge } from './ui/Badge';
import { ProgressBar } from './ui/ProgressBar';
import { Terminal, Sparkles, HelpCircle, Plus, FileSpreadsheet } from 'lucide-react';
import { CreateTransactionModal } from './CreateTransactionModal';
import { BalanceSheet } from './BalanceSheet';

export const Overview: React.FC = () => {
  const { subsidiaries, tasks, agents, leads } = useApp();
  const [isTxModalOpen, setIsTxModalOpen] = useState(false);

  const activeTasks = tasks.filter((t) => t.status === 'in_progress');

  // Filter out the 'common' pseudo-subsidiary for business-specific lists
  const businessSubs = subsidiaries.filter(s => s.id !== 'common');

  // Find top contributing subsidiary
  const topSub = [...businessSubs].sort((a, b) => b.profits - a.profits)[0];
  const totalProfits = businessSubs.reduce((sum, s) => sum + s.profits, 0) || 1;

  const totalProcurements = subsidiaries.reduce((sum, s) => sum + (s.procurements || 0), 0);
  const totalSales = subsidiaries.reduce((sum, s) => sum + (s.sales || 0), 0);
  const totalLeads = leads.length;

  return (
    <div className="space-y-6">
      {/* Overview Page Action Header */}
      <div className="flex flex-wrap justify-between items-center gap-3 bg-zinc-950/20 p-4 rounded-xl border border-zinc-900">
        <div>
          <h2 className="text-base font-bold text-zinc-100 flex items-center gap-2">
            <FileSpreadsheet size={16} className="text-purple-400" /> Parent Enterprise Control Portal
          </h2>
          <p className="text-[10px] text-zinc-500 font-mono mt-0.5">MANAGE TRANSACTION LEDGERS, TAX AUDITS, AND METRIC OVERRIDES</p>
        </div>
        <button
          onClick={() => setIsTxModalOpen(true)}
          className="px-3.5 py-2 rounded-lg bg-purple-600 hover:bg-purple-500 font-semibold text-xs text-white transition-colors flex items-center gap-1.5 shadow-lg shadow-purple-950/20 shrink-0"
        >
          <Plus size={13} /> Record Transaction
        </button>
      </div>
      {/* Operational Metrics Row */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 md:gap-6 animate-in fade-in duration-500">
        <Card className="bg-zinc-950/30 border-zinc-800/80 p-4 flex justify-between items-center">
          <div>
            <span className="text-[10px] md:text-xs text-zinc-400 font-mono uppercase tracking-wider block">Total Procurements</span>
            <div className="text-lg md:text-2xl font-bold font-mono text-indigo-400 mt-1">{totalProcurements.toLocaleString()}</div>
          </div>
          <div className="p-2.5 rounded-xl bg-zinc-900 border border-zinc-800 text-indigo-400 shrink-0 ml-2">
            🛒
          </div>
        </Card>
        <Card className="bg-zinc-950/30 border-zinc-800/80 p-4 flex justify-between items-center">
          <div>
            <span className="text-[10px] md:text-xs text-zinc-400 font-mono uppercase tracking-wider block">Total Sales</span>
            <div className="text-lg md:text-2xl font-bold font-mono text-emerald-400 mt-1">{totalSales.toLocaleString()}</div>
          </div>
          <div className="p-2.5 rounded-xl bg-zinc-900 border border-zinc-800 text-emerald-400 shrink-0 ml-2">
            📈
          </div>
        </Card>
        <Card className="bg-zinc-950/30 border-zinc-800/80 p-4 flex justify-between items-center">
          <div>
            <span className="text-[10px] md:text-xs text-zinc-400 font-mono uppercase tracking-wider block">Total Leads</span>
            <div className="text-lg md:text-2xl font-bold font-mono text-amber-400 mt-1">{totalLeads.toLocaleString()}</div>
          </div>
          <div className="p-2.5 rounded-xl bg-zinc-900 border border-zinc-800 text-amber-400 shrink-0 ml-2">
            🎯
          </div>
        </Card>
      </div>

      {/* Visual Analytics Row — stack on mobile, 3-col on large */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-5 md:gap-6">
        {/* Left widget: Contribution details */}
        <Card className="lg:col-span-2 bg-zinc-950/30 border-zinc-800/80 p-4 md:p-5 flex flex-col justify-between">
          <div>
            <div className="flex flex-wrap justify-between items-start gap-2 mb-4">
              <div>
                <h4 className="text-sm font-bold text-zinc-200">Subsidiary Performance Share</h4>
                <p className="text-[10px] text-zinc-500 font-mono mt-0.5">Share of profit generated by each business node</p>
              </div>
              {topSub && topSub.profits > 0 && (
                <div className="px-2.5 py-1 rounded bg-emerald-950/30 border border-emerald-500/20 text-emerald-400 text-[10px] font-mono flex items-center gap-1.5 shrink-0">
                  <Sparkles size={11} /> TOP: {topSub.name.toUpperCase()}
                </div>
              )}
            </div>

            {/* Performance bars */}
            <div className="space-y-4 my-2">
              {businessSubs.map((sub) => {
                const percentage = Math.round((sub.profits / totalProfits) * 100);
                return (
                  <div key={sub.id} className="space-y-1.5">
                    <div className="flex justify-between text-xs">
                      <span className="font-semibold text-zinc-300 truncate mr-2">{sub.name}</span>
                      <span className={`font-mono font-bold shrink-0 ${sub.textColor}`}>
                        ₹{sub.profits.toLocaleString()} ({percentage}%)
                      </span>
                    </div>
                    <ProgressBar
                      value={percentage}
                      color={sub.textColor.replace('text-', '').replace('-400', '') as any}
                      animate={false}
                    />
                  </div>
                );
              })}
            </div>
          </div>

          <div className="mt-4 pt-4 border-t border-zinc-900/60 flex flex-wrap items-center justify-between text-[10px] font-mono text-zinc-500 gap-2">
            <span>TOTAL PROFIT YIELD: ₹{totalProfits.toLocaleString()}</span>
            <span className="hidden sm:inline">DATA TICK HANDSHAKE: SUCCESSFUL</span>
          </div>
        </Card>

        {/* Right widget: Floating Command reference */}
        <Card className="lg:col-span-1 bg-gradient-to-br from-zinc-950/80 to-zinc-900/50 border-purple-500/10 p-4 md:p-5 relative overflow-hidden flex flex-col justify-between">
          <div className="absolute top-0 right-0 w-24 h-24 bg-purple-500/5 rounded-full blur-2xl pointer-events-none" />

          <div>
            <div className="flex items-center gap-2 mb-3.5">
              <HelpCircle size={15} className="text-purple-400" />
              <h4 className="text-xs font-bold text-zinc-300 tracking-wider font-mono uppercase">DIRECTOR_COMMAND_SHEET</h4>
            </div>

            <p className="text-[11px] text-zinc-400 leading-relaxed mb-4">
              Click the floating bubble in the bottom-right corner to issue voice or text instructions to the operations assistant.
            </p>

            {/* Command List snippets */}
            <div className="space-y-2.5 font-mono text-[9.5px]">
              <div className="p-2.5 rounded bg-zinc-950/80 border border-zinc-900 hover:border-zinc-800 transition-colors">
                <span className="text-purple-400 block font-semibold">&gt; Initialize Subsidiary</span>
                <span className="text-zinc-500 mt-1 block">"create subsidiary Robotics with 50000"</span>
              </div>
              <div className="p-2.5 rounded bg-zinc-950/80 border border-zinc-900 hover:border-zinc-800 transition-colors">
                <span className="text-purple-400 block font-semibold">&gt; Hire AI Unit</span>
                <span className="text-zinc-500 mt-1 block">"hire Developer named Jarvis for CyberCore AI"</span>
              </div>
              <div className="p-2.5 rounded bg-zinc-950/80 border border-zinc-900 hover:border-zinc-800 transition-colors">
                <span className="text-purple-400 block font-semibold">&gt; Allocate Task</span>
                <span className="text-zinc-500 mt-1 block">"assign task Launch API to Jarvis"</span>
              </div>
              <div className="p-2.5 rounded bg-zinc-950/80 border border-zinc-900 hover:border-zinc-800 transition-colors">
                <span className="text-purple-400 block font-semibold">&gt; Capital Funding</span>
                <span className="text-zinc-500 mt-1 block">"allocate 25000 to Nexus Media"</span>
              </div>
            </div>
          </div>
        </Card>
      </div>

      {/* Row 2: Live Operations Queue & Performance matrix */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-5 md:gap-6">
        {/* Left: Active tasks ticker */}
        <div className="lg:col-span-1 space-y-3">
          <h4 className="text-xs font-bold text-zinc-400 font-mono uppercase tracking-widest flex items-center gap-2">
            <Terminal size={14} className="text-purple-400" />
            Global Active Pipelines ({activeTasks.length})
          </h4>

          <div className="space-y-3 max-h-[280px] md:max-h-[360px] overflow-y-auto pr-1">
            {activeTasks.length === 0 ? (
              <div className="p-6 text-center text-xs text-zinc-600 bg-zinc-950/15 border border-dashed border-zinc-900 rounded-xl">
                All agent subroutines are resting. No active task pipelines.
              </div>
            ) : (
              activeTasks.map((task) => {
                const sub = subsidiaries.find(s => s.id === task.subsidiaryId);
                const agent = agents.find(a => a.id === task.assignedAgentId);
                return (
                  <Card key={task.id} className="p-3.5 bg-zinc-950/40 border-zinc-900 hover:border-zinc-800/80 transition-colors">
                    <div className="flex justify-between items-start">
                      <div>
                        <span className={`px-1.5 py-0.5 rounded text-[8px] font-mono leading-none tracking-tight font-semibold bg-zinc-900 border border-zinc-800 ${sub?.textColor} shrink-0`}>
                          {sub?.name}
                        </span>
                        <h5 className="text-xs font-bold text-zinc-200 mt-2">{task.title}</h5>
                      </div>
                      <Badge variant="in_progress">{task.progress}%</Badge>
                    </div>

                    <div className="flex items-center justify-between text-[9px] text-zinc-500 font-mono mt-3.5 pt-2 border-t border-zinc-900/60">
                      <span>Agent: {agent?.name}</span>
                      <span className="text-emerald-400 font-semibold">+₹{task.payout.toLocaleString()}</span>
                    </div>
                  </Card>
                );
              })
            )}
          </div>
        </div>

        {/* Right: Detailed Subsidiary Ledger — scrolls horizontally on small screens */}
        <div className="lg:col-span-2 space-y-3">
          <h4 className="text-xs font-bold text-zinc-400 font-mono uppercase tracking-widest flex items-center gap-2">
            Ledger Audit Index
          </h4>

          <div className="overflow-x-auto rounded-xl border border-zinc-900 bg-zinc-950/30">
            <table className="w-full min-w-[480px] text-left border-collapse text-xs select-text">
              <thead>
                <tr className="bg-zinc-950/60 border-b border-zinc-900 text-zinc-500 font-mono text-[10px]">
                  <th className="p-3 pl-4">SUBSIDIARY NODE</th>
                  <th className="p-3">BALANCE</th>
                  <th className="p-3">SEED CAP</th>
                  <th className="p-3 text-rose-400">EXPENSES</th>
                  <th className="p-3 text-emerald-400">NET PROFITS</th>
                  <th className="p-3 pr-4 text-right">NET CAP</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-zinc-900/60">
                {businessSubs.map((sub) => {
                  const netVal = sub.balance + sub.profits - sub.expenses;
                  return (
                    <tr key={sub.id} className="hover:bg-zinc-900/20 text-zinc-300 font-mono transition-colors">
                      <td className="p-3 pl-4 font-sans font-bold text-zinc-100 flex items-center gap-2">
                        <span className={`w-1.5 h-1.5 rounded-full shrink-0 ${sub.textColor.replace('text-', 'bg-')}`} />
                        {sub.name}
                      </td>
                      <td className="p-3 font-semibold text-zinc-200">₹{sub.balance.toLocaleString()}</td>
                      <td className="p-3 text-zinc-400">₹{sub.investment.toLocaleString()}</td>
                      <td className="p-3 text-rose-400/90">₹{sub.expenses.toLocaleString()}</td>
                      <td className="p-3 text-emerald-400/90">₹{sub.profits.toLocaleString()}</td>
                      <td className="p-3 pr-4 text-right font-bold text-zinc-100">₹{netVal.toLocaleString()}</td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      </div>

      {/* Consolidated Balance Sheet */}
      <div className="space-y-3 animate-in fade-in duration-500 delay-100">
        <h4 className="text-xs font-bold text-zinc-400 font-mono uppercase tracking-widest flex items-center gap-2">
          Consolidated Ledger & Balance Sheet Audit
        </h4>
        <BalanceSheet />
      </div>

      {/* Transaction Entry Modal */}
      <CreateTransactionModal
        isOpen={isTxModalOpen}
        onClose={() => setIsTxModalOpen(false)}
      />
    </div>
  );
};
