#!/bin/bash
BASE="http://localhost:5035/api/simulation/roles"
POST() { curl -s -o /dev/null -w "%{http_code}" -X POST "$BASE" -H "Content-Type: application/json" -d "$1"; }

declare -a ROLES=(
# ── Core 10 ──────────────────────────────────────────────────────────────────
'{"id":"ceo","name":"CEO","commonSkills":["Strategic Planning","Leadership","Decision Making","Stakeholder Management","Vision Setting","OKR Alignment","Board Communication"],"temperature":0.5,"maxTokens":2048,"outputFormat":"markdown","memoryType":"long_term","tools":[{"name":"read_reports","description":"Read financial and operational reports","enabled":true},{"name":"send_directive","description":"Issue directives to subordinate agents","enabled":true},{"name":"web_search","description":"Search for market intelligence","enabled":true}]}'

'{"id":"cfo","name":"CFO","commonSkills":["Financial Analysis","Budget Allocation","Risk Assessment","Cost Optimization","Forecasting","P&L Management","Tax Planning"],"temperature":0.2,"maxTokens":1024,"outputFormat":"json","memoryType":"long_term","tools":[{"name":"read_ledger","description":"Access the subsidiary financial ledger","enabled":true},{"name":"generate_report","description":"Generate formatted financial reports","enabled":true},{"name":"alert_ceo","description":"Send budget alerts to the CEO","enabled":true}]}'

'{"id":"cto","name":"CTO","commonSkills":["System Architecture","AI/ML Pipelines","DevOps","Code Review","Tech Strategy","Cloud Infrastructure","Security Posture"],"temperature":0.3,"maxTokens":4096,"outputFormat":"code","memoryType":"short_term","tools":[{"name":"code_exec","description":"Execute code in a sandboxed runtime","enabled":true},{"name":"read_codebase","description":"Read source files from the repository","enabled":true},{"name":"web_search","description":"Search docs and Stack Overflow","enabled":true},{"name":"deploy_service","description":"Trigger CI/CD deployment pipeline","enabled":false}]}'

'{"id":"cmo","name":"CMO","commonSkills":["Brand Strategy","Growth Marketing","Campaign Management","SEO/SEM","Audience Analytics","Funnel Optimization","Media Buying"],"temperature":0.7,"maxTokens":2048,"outputFormat":"markdown","memoryType":"short_term","tools":[{"name":"web_search","description":"Research trends and competitor activity","enabled":true},{"name":"generate_copy","description":"Generate ad and content copy","enabled":true},{"name":"send_email","description":"Send campaign emails","enabled":false}]}'

'{"id":"product-manager","name":"Product Manager","commonSkills":["Roadmap Planning","User Research","Sprint Management","Backlog Grooming","OKR Setting","Feature Prioritization","Stakeholder Alignment"],"temperature":0.5,"maxTokens":2048,"outputFormat":"markdown","memoryType":"long_term","tools":[{"name":"read_backlog","description":"Read and prioritize the task backlog","enabled":true},{"name":"write_spec","description":"Write user story or feature specification","enabled":true},{"name":"web_search","description":"Research competitors and user feedback","enabled":true}]}'

'{"id":"developer","name":"Developer","commonSkills":["Full-Stack Development","API Design","Unit Testing","CI/CD","Database Optimization","Code Review","Debugging"],"temperature":0.2,"maxTokens":8192,"outputFormat":"code","memoryType":"short_term","tools":[{"name":"code_exec","description":"Execute code in a sandboxed runtime","enabled":true},{"name":"read_codebase","description":"Read files from the project repository","enabled":true},{"name":"write_file","description":"Write or patch source files","enabled":true},{"name":"web_search","description":"Search documentation and GitHub issues","enabled":true},{"name":"run_tests","description":"Run automated test suites","enabled":true}]}'

'{"id":"ui-designer","name":"UI Designer","commonSkills":["UI/UX Design","Figma Prototyping","Design Systems","Accessibility","Micro-animations","Typography","Color Theory"],"temperature":0.9,"maxTokens":2048,"outputFormat":"markdown","memoryType":"none","tools":[{"name":"generate_image","description":"Generate UI mockup images via AI","enabled":true},{"name":"web_search","description":"Search design inspiration and libraries","enabled":true},{"name":"write_file","description":"Write CSS and component files","enabled":false}]}'

'{"id":"marketer","name":"Marketer","commonSkills":["Content Creation","Social Media","Email Campaigns","Copywriting","A/B Testing","Lead Generation","Analytics"],"temperature":0.8,"maxTokens":1024,"outputFormat":"plain","memoryType":"none","tools":[{"name":"generate_copy","description":"Write marketing copy","enabled":true},{"name":"web_search","description":"Research trends and keywords","enabled":true},{"name":"send_email","description":"Send newsletter or campaign emails","enabled":false}]}'

'{"id":"qa-engineer","name":"QA Engineer","commonSkills":["Test Automation","Regression Testing","Bug Reporting","Performance Testing","API Testing","Selenium/Playwright","Test Plan Design"],"temperature":0.1,"maxTokens":4096,"outputFormat":"json","memoryType":"short_term","tools":[{"name":"run_tests","description":"Execute automated test suites","enabled":true},{"name":"read_codebase","description":"Inspect source code for issues","enabled":true},{"name":"file_bug","description":"File a bug report in the tracker","enabled":true},{"name":"code_exec","description":"Run scripts for performance profiling","enabled":true}]}'

'{"id":"customer-support","name":"Customer Support","commonSkills":["Ticket Resolution","Knowledge Base","SLA Management","Customer Empathy","Escalation Handling","CRM Usage","NPS Tracking"],"temperature":0.4,"maxTokens":512,"outputFormat":"plain","memoryType":"short_term","tools":[{"name":"read_kb","description":"Read knowledge base articles","enabled":true},{"name":"send_email","description":"Reply to customer tickets via email","enabled":true},{"name":"escalate","description":"Escalate unresolved tickets to a human","enabled":true}]}'

# ── Extended 50 ───────────────────────────────────────────────────────────────
'{"id":"designer","name":"Designer","commonSkills":["Visual Design","Brand Identity","Print & Digital Design","Typography","Color Theory","Layout Composition","Asset Production"],"temperature":0.88,"maxTokens":2048,"outputFormat":"markdown","memoryType":"none","tools":[{"name":"generate_image","description":"Generate visual design assets","enabled":true},{"name":"web_search","description":"Search design references and inspirations","enabled":true}]}'

'{"id":"supervisor","name":"Supervisor","commonSkills":["Team Oversight","Task Delegation","Performance Reviews","Conflict Resolution","SOP Compliance","Shift Planning","KPI Monitoring"],"temperature":0.4,"maxTokens":2048,"outputFormat":"markdown","memoryType":"long_term","tools":[{"name":"read_reports","description":"Read team performance and task reports","enabled":true},{"name":"send_directive","description":"Issue directives to team members","enabled":true},{"name":"web_search","description":"Research best management practices","enabled":true}]}'

'{"id":"system-administrator","name":"System Administrator","commonSkills":["Server Management","Network Configuration","OS Administration","Backup & Recovery","User Access Control","Patch Management","Monitoring & Alerting"],"temperature":0.2,"maxTokens":4096,"outputFormat":"code","memoryType":"short_term","tools":[{"name":"code_exec","description":"Run sysadmin scripts and commands","enabled":true},{"name":"read_codebase","description":"Read configuration files and infrastructure code","enabled":true},{"name":"web_search","description":"Research OS and network troubleshooting guides","enabled":true}]}'

'{"id":"database-administrator","name":"Database Administrator","commonSkills":["SQL & NoSQL","Query Optimization","Schema Design","Backup & Recovery","Replication & Clustering","Performance Tuning","Data Integrity"],"temperature":0.15,"maxTokens":4096,"outputFormat":"code","memoryType":"short_term","tools":[{"name":"code_exec","description":"Execute database queries and admin scripts","enabled":true},{"name":"read_codebase","description":"Review schema and migration files","enabled":true},{"name":"web_search","description":"Research DB performance and indexing strategies","enabled":true}]}'

'{"id":"security-analyst","name":"Security Analyst","commonSkills":["Threat Detection","Vulnerability Assessment","SIEM Tools","Incident Response","Penetration Testing","Compliance (ISO 27001, SOC2)","Risk Mitigation"],"temperature":0.2,"maxTokens":4096,"outputFormat":"json","memoryType":"long_term","tools":[{"name":"code_exec","description":"Run security scans and audit scripts","enabled":true},{"name":"read_codebase","description":"Review code for security vulnerabilities","enabled":true},{"name":"web_search","description":"Research CVEs and threat intelligence feeds","enabled":true},{"name":"file_bug","description":"File security incident reports","enabled":true}]}'

'{"id":"sales-representative","name":"Sales Representative","commonSkills":["Prospecting","Cold Outreach","Objection Handling","CRM Management","Pipeline Management","Negotiation","Closing Techniques"],"temperature":0.65,"maxTokens":1024,"outputFormat":"plain","memoryType":"short_term","tools":[{"name":"web_search","description":"Research prospect companies and contacts","enabled":true},{"name":"send_email","description":"Send prospecting and follow-up emails","enabled":true},{"name":"generate_copy","description":"Draft sales scripts and outreach messages","enabled":true}]}'

'{"id":"hr-specialist","name":"HR Specialist","commonSkills":["Recruitment & Onboarding","Employee Relations","Payroll Administration","Benefits Management","Policy Compliance","Performance Management","Training & Development"],"temperature":0.45,"maxTokens":1024,"outputFormat":"plain","memoryType":"long_term","tools":[{"name":"web_search","description":"Research HR policies and labor laws","enabled":true},{"name":"send_email","description":"Send offer letters and HR communications","enabled":true},{"name":"generate_copy","description":"Draft job descriptions and HR documents","enabled":true}]}'

'{"id":"copywriter","name":"Copywriter","commonSkills":["Persuasive Writing","Headline Crafting","Value Proposition","Ad Copy","Landing Page Copy","Email Sequences","Brand Voice"],"temperature":0.82,"maxTokens":2048,"outputFormat":"plain","memoryType":"none","tools":[{"name":"generate_copy","description":"Draft persuasive copy for ads, emails, and landing pages","enabled":true},{"name":"web_search","description":"Research audience, competitors, and trending angles","enabled":true}]}'

'{"id":"social-media-specialist","name":"Social Media Specialist","commonSkills":["Platform Strategy (Instagram, LinkedIn, X, TikTok)","Content Scheduling","Community Management","Hashtag Research","Engagement Analytics","Influencer Coordination","Viral Content Design"],"temperature":0.85,"maxTokens":1024,"outputFormat":"plain","memoryType":"short_term","tools":[{"name":"web_search","description":"Research trending content and hashtags","enabled":true},{"name":"generate_copy","description":"Draft social media posts and captions","enabled":true},{"name":"generate_image","description":"Generate social media visuals","enabled":true}]}'

'{"id":"data-scientist","name":"Data Scientist","commonSkills":["Machine Learning","Statistical Analysis","Python & R","Data Pipeline Design","Feature Engineering","Model Evaluation","Experiment Design"],"temperature":0.3,"maxTokens":4096,"outputFormat":"code","memoryType":"long_term","tools":[{"name":"code_exec","description":"Run ML experiments and data analysis scripts","enabled":true},{"name":"web_search","description":"Research datasets, papers, and model architectures","enabled":true},{"name":"read_codebase","description":"Review existing models and pipelines","enabled":true}]}'

'{"id":"data-analyst","name":"Data Analyst","commonSkills":["SQL","Excel & Google Sheets","Data Visualization (Tableau, Power BI)","KPI Dashboards","A/B Test Analysis","Business Intelligence","Trend Reporting"],"temperature":0.25,"maxTokens":2048,"outputFormat":"json","memoryType":"short_term","tools":[{"name":"code_exec","description":"Run SQL queries and data transformation scripts","enabled":true},{"name":"generate_report","description":"Generate analytics summaries and dashboards","enabled":true},{"name":"web_search","description":"Research BI methodologies and data sources","enabled":true}]}'

'{"id":"devops-engineer","name":"DevOps Engineer","commonSkills":["CI/CD Pipelines","Docker & Kubernetes","Infrastructure as Code (Terraform)","Cloud Platforms (AWS/GCP/Azure)","Monitoring & Logging","Site Reliability","Release Management"],"temperature":0.2,"maxTokens":4096,"outputFormat":"code","memoryType":"short_term","tools":[{"name":"code_exec","description":"Execute deployment scripts and infrastructure commands","enabled":true},{"name":"read_codebase","description":"Review pipeline configs and IaC scripts","enabled":true},{"name":"web_search","description":"Research DevOps tools and cloud documentation","enabled":true},{"name":"deploy_service","description":"Trigger CI/CD pipeline runs","enabled":true}]}'

'{"id":"customer-success-manager","name":"Customer Success Manager","commonSkills":["Onboarding","Relationship Management","Churn Prevention","NPS & CSAT Tracking","Upselling","QBR Facilitation","Product Adoption Coaching"],"temperature":0.5,"maxTokens":1024,"outputFormat":"plain","memoryType":"long_term","tools":[{"name":"read_kb","description":"Reference product documentation and guides","enabled":true},{"name":"send_email","description":"Communicate with customers for check-ins and renewals","enabled":true},{"name":"web_search","description":"Research customer industry news and context","enabled":true}]}'

'{"id":"solutions-architect","name":"Solutions Architect","commonSkills":["Enterprise Architecture","Cloud Design Patterns","API Integration","System Scalability","Technical Presales","Vendor Evaluation","PoC Development"],"temperature":0.35,"maxTokens":4096,"outputFormat":"markdown","memoryType":"long_term","tools":[{"name":"code_exec","description":"Build and test proof-of-concept implementations","enabled":true},{"name":"read_codebase","description":"Review existing system architecture","enabled":true},{"name":"web_search","description":"Research cloud services and integration patterns","enabled":true}]}'

'{"id":"product-marketing-specialist","name":"Product Marketing Specialist","commonSkills":["Go-to-Market Strategy","Competitive Positioning","Messaging & Positioning","Launch Planning","Win/Loss Analysis","Sales Enablement","Analyst Relations"],"temperature":0.65,"maxTokens":2048,"outputFormat":"markdown","memoryType":"short_term","tools":[{"name":"web_search","description":"Research competitors, market positioning, and customer segments","enabled":true},{"name":"generate_copy","description":"Write product messaging, one-pagers, and launch content","enabled":true},{"name":"send_email","description":"Coordinate with sales and marketing teams","enabled":false}]}'

'{"id":"business-analyst","name":"Business Analyst","commonSkills":["Requirements Gathering","Process Mapping","Gap Analysis","Use Case Documentation","Stakeholder Interviews","Data Reporting","Agile & Waterfall"],"temperature":0.4,"maxTokens":2048,"outputFormat":"markdown","memoryType":"long_term","tools":[{"name":"web_search","description":"Research industry standards and business processes","enabled":true},{"name":"generate_copy","description":"Document BRDs, user stories, and process flows","enabled":true},{"name":"write_file","description":"Save requirements documents and specs","enabled":true}]}'

'{"id":"tech-lead","name":"Tech Lead","commonSkills":["Technical Direction","Code Review","Architecture Decision Records","Mentoring","Sprint Planning","Cross-team Coordination","System Design"],"temperature":0.3,"maxTokens":4096,"outputFormat":"code","memoryType":"long_term","tools":[{"name":"read_codebase","description":"Review architecture and codebase quality","enabled":true},{"name":"code_exec","description":"Run validation scripts and technical demos","enabled":true},{"name":"web_search","description":"Research engineering best practices","enabled":true},{"name":"write_file","description":"Write ADRs and technical documentation","enabled":true}]}'

'{"id":"scrum-master","name":"Scrum Master","commonSkills":["Agile Facilitation","Sprint Ceremonies","Backlog Refinement","Velocity Tracking","Impediment Removal","Team Coaching","Retrospective Facilitation"],"temperature":0.45,"maxTokens":1024,"outputFormat":"markdown","memoryType":"short_term","tools":[{"name":"read_backlog","description":"Access and manage the sprint backlog","enabled":true},{"name":"generate_copy","description":"Document sprint reports and ceremony notes","enabled":true},{"name":"web_search","description":"Research agile frameworks and coaching techniques","enabled":true}]}'

'{"id":"project-manager","name":"Project Manager","commonSkills":["Project Scoping","Resource Planning","Risk Management","Timeline Management","Stakeholder Reporting","Budget Tracking","PMP/PRINCE2"],"temperature":0.4,"maxTokens":2048,"outputFormat":"markdown","memoryType":"long_term","tools":[{"name":"read_reports","description":"Read project status and resource reports","enabled":true},{"name":"send_email","description":"Send stakeholder updates and escalations","enabled":true},{"name":"web_search","description":"Research project management methodologies","enabled":true},{"name":"generate_copy","description":"Draft project plans and status reports","enabled":true}]}'

'{"id":"legal-counsel","name":"Legal Counsel","commonSkills":["Contract Review","Compliance Management","IP & Trademark","Employment Law","GDPR/Privacy","Regulatory Affairs","Dispute Resolution"],"temperature":0.15,"maxTokens":2048,"outputFormat":"plain","memoryType":"long_term","tools":[{"name":"web_search","description":"Research case law, regulations, and legal precedents","enabled":true},{"name":"generate_copy","description":"Draft contract clauses, NDAs, and legal notices","enabled":true},{"name":"write_file","description":"Save legal documents and compliance records","enabled":true}]}'

'{"id":"seo-specialist","name":"SEO Specialist","commonSkills":["Keyword Research","On-page Optimization","Technical SEO","Link Building","SERP Analysis","Content Audit","GA4 & Search Console"],"temperature":0.55,"maxTokens":2048,"outputFormat":"markdown","memoryType":"short_term","tools":[{"name":"web_search","description":"Research keywords, SERPs, and competitor backlinks","enabled":true},{"name":"generate_copy","description":"Write SEO-optimized content briefs and meta tags","enabled":true},{"name":"write_file","description":"Save keyword research reports and content calendars","enabled":true}]}'

'{"id":"content-strategist","name":"Content Strategist","commonSkills":["Content Architecture","Audience Persona Development","Content Gap Analysis","Editorial Planning","Multi-channel Strategy","Measurement & ROI","Brand Narrative"],"temperature":0.7,"maxTokens":2048,"outputFormat":"markdown","memoryType":"long_term","tools":[{"name":"web_search","description":"Research audience behavior, trends, and competitor content","enabled":true},{"name":"generate_copy","description":"Draft content strategies, briefs, and editorial frameworks","enabled":true},{"name":"write_file","description":"Save content plans and strategy documents","enabled":true}]}'

'{"id":"video-editor","name":"Video Editor","commonSkills":["Non-linear Editing (Premiere, DaVinci)","Color Grading","Audio Mixing","Motion Graphics","Storyboarding","Subtitle & Captioning","Export & Delivery Formats"],"temperature":0.75,"maxTokens":1024,"outputFormat":"plain","memoryType":"none","tools":[{"name":"generate_image","description":"Generate thumbnail and motion graphic assets","enabled":true},{"name":"web_search","description":"Research editing techniques and stock assets","enabled":true},{"name":"write_file","description":"Save edit notes and project timelines","enabled":true}]}'

'{"id":"prompt-engineer","name":"Prompt Engineer","commonSkills":["Prompt Design & Optimization","Few-Shot & Zero-Shot Learning","Chain-of-Thought Prompting","LLM Evaluation","Jailbreak Prevention","RAG Design","Instruction Tuning"],"temperature":0.5,"maxTokens":4096,"outputFormat":"markdown","memoryType":"long_term","tools":[{"name":"code_exec","description":"Test prompts programmatically via API","enabled":true},{"name":"web_search","description":"Research LLM capabilities, papers, and prompt techniques","enabled":true},{"name":"write_file","description":"Document prompt libraries and evaluation results","enabled":true}]}'

'{"id":"ml-engineer","name":"ML Engineer","commonSkills":["Model Training & Fine-tuning","PyTorch/TensorFlow","MLOps & Model Serving","Data Engineering","Hyperparameter Tuning","Experiment Tracking (MLflow)","Quantization & Optimization"],"temperature":0.25,"maxTokens":8192,"outputFormat":"code","memoryType":"long_term","tools":[{"name":"code_exec","description":"Run model training and evaluation scripts","enabled":true},{"name":"read_codebase","description":"Review model architecture and training pipelines","enabled":true},{"name":"web_search","description":"Research ML papers and framework documentation","enabled":true}]}'

'{"id":"full-stack-developer","name":"Full-Stack Developer","commonSkills":["Frontend (React/Vue/Angular)","Backend (Node/Django/.NET)","REST & GraphQL APIs","Database Design","Cloud Deployment","Authentication & Security","Test-Driven Development"],"temperature":0.25,"maxTokens":8192,"outputFormat":"code","memoryType":"short_term","tools":[{"name":"code_exec","description":"Execute code in sandboxed runtime","enabled":true},{"name":"read_codebase","description":"Read and review project files","enabled":true},{"name":"write_file","description":"Write and patch source files","enabled":true},{"name":"run_tests","description":"Run test suites","enabled":true},{"name":"web_search","description":"Search docs and Stack Overflow","enabled":true}]}'

'{"id":"frontend-developer","name":"Frontend Developer","commonSkills":["React/Vue/Angular","HTML5 & CSS3","TypeScript","State Management (Redux/Zustand)","Component Design","Performance Optimization","Accessibility (WCAG)"],"temperature":0.25,"maxTokens":4096,"outputFormat":"code","memoryType":"short_term","tools":[{"name":"code_exec","description":"Run frontend build and test commands","enabled":true},{"name":"read_codebase","description":"Review component and style source files","enabled":true},{"name":"write_file","description":"Write and patch frontend components","enabled":true},{"name":"web_search","description":"Search MDN, component docs, and design systems","enabled":true}]}'

'{"id":"backend-developer","name":"Backend Developer","commonSkills":["REST API Design","Microservices","Database Modeling","Authentication (OAuth/JWT)","Message Queues","Caching (Redis)","API Security"],"temperature":0.2,"maxTokens":4096,"outputFormat":"code","memoryType":"short_term","tools":[{"name":"code_exec","description":"Run backend scripts and migration commands","enabled":true},{"name":"read_codebase","description":"Review server-side code and schemas","enabled":true},{"name":"write_file","description":"Write API routes and service logic","enabled":true},{"name":"run_tests","description":"Run API and integration tests","enabled":true}]}'

'{"id":"mobile-developer","name":"Mobile Developer","commonSkills":["iOS (Swift/SwiftUI)","Android (Kotlin/Jetpack)","React Native / Flutter","App Store Deployment","Push Notifications","Offline Storage","Performance Profiling"],"temperature":0.25,"maxTokens":4096,"outputFormat":"code","memoryType":"short_term","tools":[{"name":"code_exec","description":"Build and test mobile app modules","enabled":true},{"name":"read_codebase","description":"Review mobile source and config files","enabled":true},{"name":"web_search","description":"Search mobile platform docs and community solutions","enabled":true}]}'

'{"id":"infrastructure-engineer","name":"Infrastructure Engineer","commonSkills":["Cloud Architecture (AWS/GCP/Azure)","Networking (VPC, DNS, Load Balancers)","Terraform / Pulumi","Kubernetes & Helm","Cost Optimization","Disaster Recovery","Capacity Planning"],"temperature":0.2,"maxTokens":4096,"outputFormat":"code","memoryType":"long_term","tools":[{"name":"code_exec","description":"Run infrastructure provisioning scripts","enabled":true},{"name":"read_codebase","description":"Review IaC files and cloud configs","enabled":true},{"name":"web_search","description":"Research cloud services and pricing","enabled":true},{"name":"deploy_service","description":"Trigger infrastructure deployments","enabled":true}]}'

'{"id":"technical-writer","name":"Technical Writer","commonSkills":["API Documentation","User Guides","Release Notes","Docs-as-Code (Markdown/AsciiDoc)","Information Architecture","Style Guides","Diagramming (Mermaid, Lucidchart)"],"temperature":0.5,"maxTokens":2048,"outputFormat":"markdown","memoryType":"short_term","tools":[{"name":"read_codebase","description":"Read source code for accurate documentation","enabled":true},{"name":"write_file","description":"Write and update documentation files","enabled":true},{"name":"web_search","description":"Research technical concepts and terminology","enabled":true}]}'

'{"id":"support-tier-2-specialist","name":"Support Tier 2 Specialist","commonSkills":["Advanced Troubleshooting","Escalation Handling","Root Cause Analysis","Log Analysis","Customer Communication","Bug Triage","Internal Knowledge Sharing"],"temperature":0.35,"maxTokens":1024,"outputFormat":"plain","memoryType":"short_term","tools":[{"name":"read_kb","description":"Reference advanced technical knowledge base","enabled":true},{"name":"send_email","description":"Communicate resolution steps to customer","enabled":true},{"name":"file_bug","description":"File detailed bug reports for engineering","enabled":true}]}'

'{"id":"growth-hacker","name":"Growth Hacker","commonSkills":["Viral Loop Design","Referral Programs","Conversion Rate Optimization","Product-Led Growth","Funnel Analytics","A/B Testing","Activation & Retention Strategies"],"temperature":0.8,"maxTokens":2048,"outputFormat":"markdown","memoryType":"short_term","tools":[{"name":"web_search","description":"Research growth experiments and competitor strategies","enabled":true},{"name":"generate_copy","description":"Write landing pages and onboarding copy","enabled":true},{"name":"code_exec","description":"Run analytics queries and experiment scripts","enabled":true}]}'

'{"id":"event-coordinator","name":"Event Coordinator","commonSkills":["Event Planning","Vendor Management","Budget Tracking","Logistics & Scheduling","Guest Experience","On-site Coordination","Post-event Reporting"],"temperature":0.55,"maxTokens":1024,"outputFormat":"plain","memoryType":"short_term","tools":[{"name":"web_search","description":"Research venues, vendors, and event best practices","enabled":true},{"name":"send_email","description":"Coordinate with vendors and attendees","enabled":true},{"name":"generate_copy","description":"Draft event communications and run-of-show documents","enabled":true}]}'

'{"id":"public-relations-specialist","name":"Public Relations Specialist","commonSkills":["Media Relations","Press Release Writing","Crisis Communication","Reputation Management","Influencer Outreach","Brand Storytelling","Editorial Coverage"],"temperature":0.7,"maxTokens":1024,"outputFormat":"plain","memoryType":"short_term","tools":[{"name":"web_search","description":"Monitor media coverage and journalist contacts","enabled":true},{"name":"generate_copy","description":"Draft press releases, pitches, and statements","enabled":true},{"name":"send_email","description":"Pitch journalists and media contacts","enabled":false}]}'

'{"id":"operations-coordinator","name":"Operations Coordinator","commonSkills":["Process Documentation","Workflow Optimization","Vendor Coordination","Data Entry & Reporting","Cross-department Liaison","SOP Development","Resource Scheduling"],"temperature":0.4,"maxTokens":1024,"outputFormat":"plain","memoryType":"short_term","tools":[{"name":"web_search","description":"Research operational best practices","enabled":true},{"name":"generate_copy","description":"Draft SOPs and process documentation","enabled":true},{"name":"write_file","description":"Save operational checklists and schedules","enabled":true}]}'

'{"id":"financial-controller","name":"Financial Controller","commonSkills":["Month-end Close","Financial Reporting","GAAP/IFRS Compliance","Accounts Payable & Receivable","Internal Controls","Audit Preparation","Cash Flow Management"],"temperature":0.15,"maxTokens":2048,"outputFormat":"json","memoryType":"long_term","tools":[{"name":"read_ledger","description":"Access detailed financial ledgers","enabled":true},{"name":"generate_report","description":"Generate financial statements and compliance reports","enabled":true},{"name":"web_search","description":"Research accounting standards and tax regulations","enabled":true}]}'

'{"id":"auditor","name":"Auditor","commonSkills":["Internal & External Audits","Risk Assessment","Compliance Verification","Evidence Collection","Financial Statement Review","Fraud Detection","Audit Trail Analysis"],"temperature":0.1,"maxTokens":2048,"outputFormat":"json","memoryType":"long_term","tools":[{"name":"read_ledger","description":"Inspect financial records and transaction logs","enabled":true},{"name":"generate_report","description":"Produce audit findings and compliance reports","enabled":true},{"name":"web_search","description":"Research audit standards (IAS, GAAS)","enabled":true},{"name":"file_bug","description":"File compliance exceptions and audit issues","enabled":true}]}'

'{"id":"business-development-manager","name":"Business Development Manager","commonSkills":["Partnership Development","Market Expansion","Deal Structuring","Lead Qualification","Revenue Growth","Strategic Alliances","Contract Negotiation"],"temperature":0.6,"maxTokens":2048,"outputFormat":"markdown","memoryType":"long_term","tools":[{"name":"web_search","description":"Research market opportunities and partner profiles","enabled":true},{"name":"generate_copy","description":"Draft partnership proposals and decks","enabled":true},{"name":"send_email","description":"Reach out to potential partners and prospects","enabled":true}]}'

'{"id":"account-executive","name":"Account Executive","commonSkills":["Enterprise Sales","Demo & Discovery Calls","Proposal Writing","Contract Negotiation","Quota Achievement","CRM Hygiene","Multi-stakeholder Selling"],"temperature":0.6,"maxTokens":1024,"outputFormat":"plain","memoryType":"short_term","tools":[{"name":"web_search","description":"Research accounts and stakeholders before calls","enabled":true},{"name":"generate_copy","description":"Write personalized proposals and follow-ups","enabled":true},{"name":"send_email","description":"Send outreach, follow-ups, and contract emails","enabled":true}]}'

'{"id":"graphic-designer","name":"Graphic Designer","commonSkills":["Adobe Creative Suite","Brand Identity Design","Print Production","Packaging Design","Illustration","Motion Graphics","Asset Versioning"],"temperature":0.85,"maxTokens":2048,"outputFormat":"plain","memoryType":"none","tools":[{"name":"generate_image","description":"Generate and iterate on visual design concepts","enabled":true},{"name":"web_search","description":"Research design trends and stock resources","enabled":true},{"name":"write_file","description":"Export and save design deliverables","enabled":false}]}'

'{"id":"brand-ambassador","name":"Brand Ambassador","commonSkills":["Product Evangelism","Community Engagement","Event Representation","User Testimonials","Social Proof Creation","Partner Co-marketing","Influencer Collaboration"],"temperature":0.8,"maxTokens":1024,"outputFormat":"plain","memoryType":"none","tools":[{"name":"web_search","description":"Monitor brand mentions and community conversations","enabled":true},{"name":"generate_copy","description":"Write testimonials, posts, and brand content","enabled":true},{"name":"send_email","description":"Coordinate with marketing and PR teams","enabled":false}]}'

'{"id":"email-marketer","name":"Email Marketer","commonSkills":["Email Campaign Strategy","List Segmentation","Drip Sequences","Open Rate Optimization","A/B Subject Line Testing","HTML Email Templates","ESP Tools (Mailchimp, Klaviyo)"],"temperature":0.75,"maxTokens":1024,"outputFormat":"plain","memoryType":"short_term","tools":[{"name":"generate_copy","description":"Write email sequences and newsletters","enabled":true},{"name":"web_search","description":"Research audience segmentation and deliverability best practices","enabled":true},{"name":"send_email","description":"Send test and campaign emails","enabled":false}]}'

'{"id":"automation-engineer","name":"Automation Engineer","commonSkills":["RPA (UiPath, Automation Anywhere)","Workflow Automation","API Integration","Process Scripting","Error Handling","Bot Maintenance","Zapier/Make Workflows"],"temperature":0.2,"maxTokens":4096,"outputFormat":"code","memoryType":"short_term","tools":[{"name":"code_exec","description":"Build and test automation scripts","enabled":true},{"name":"read_codebase","description":"Review existing automation flows and integrations","enabled":true},{"name":"web_search","description":"Research automation tools and APIs","enabled":true}]}'

'{"id":"risk-manager","name":"Risk Manager","commonSkills":["Risk Identification & Scoring","Business Continuity Planning","Regulatory Compliance","Insurance Assessment","Crisis Management","Risk Register Management","Scenario Analysis"],"temperature":0.2,"maxTokens":2048,"outputFormat":"json","memoryType":"long_term","tools":[{"name":"web_search","description":"Research regulatory changes and industry risk benchmarks","enabled":true},{"name":"generate_report","description":"Produce risk assessments and mitigation plans","enabled":true},{"name":"write_file","description":"Maintain the risk register and incident logs","enabled":true}]}'

'{"id":"research-scientist","name":"Research Scientist","commonSkills":["Hypothesis Design","Experimental Methodology","Literature Review","Peer Review","Data Analysis (R/Python)","Academic Writing","Grant & Proposal Writing"],"temperature":0.4,"maxTokens":4096,"outputFormat":"markdown","memoryType":"long_term","tools":[{"name":"web_search","description":"Search academic papers, datasets, and research databases","enabled":true},{"name":"code_exec","description":"Run statistical analysis and simulation scripts","enabled":true},{"name":"write_file","description":"Draft research papers and findings reports","enabled":true}]}'
)

total=${#ROLES[@]}
success=0
skip=0
fail=0

for role in "${ROLES[@]}"; do
  name=$(echo "$role" | python3 -c "import json,sys; print(json.load(sys.stdin)['name'])" 2>/dev/null)
  code=$(POST "$role")
  if [ "$code" = "200" ] || [ "$code" = "201" ]; then
    echo "  ✅ $name"
    ((success++))
  elif [ "$code" = "409" ]; then
    echo "  ⏭  $name (already exists)"
    ((skip++))
  else
    echo "  ❌ $name (HTTP $code)"
    ((fail++))
  fi
done

echo ""
echo "─────────────────────────────────────"
echo "Done: $success seeded | $skip skipped | $fail failed | $total total"
